- id: '32412341222'
  alias: Play Radio Energy Zürich
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.play_energy_zurich_everywhere
    to: 'on'
  action:
  - service: tts.google_say
    entity_id: media_player.everywhere
    data:
      message: Playing Energy Zürich on everywhere
  - service: media_player.play_media
    data:
      entity_id: media_player.everywhere
      media_content_id: https://energyzuerich.ice.infomaniak.ch/energyzuerich-high.mp3
      media_content_type: audio/mp4
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.play_energy_zurich_everywhere
- id: '1665595395896'
  alias: Turn lights off when it's bright outside
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:50
  condition:
  - condition: state
    entity_id: weather.dark_sky
    state: clear-night
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - 7fbcb16a73504d41a2e21a66bc6b425a
      - dda5eecbe02041cc9604f7f238d33cdb
      - 5ded8f5066b84088845f6ca7b02c4f3b
      - 20abfdaf54874e2ca6c26c5264f60816
      - dfd5dc1121b74e9c999682e794bc6cbe
  mode: single
- id: '1667820246103'
  alias: Toothbrush Announcement
  description: Announces when teeth are brushed
  trigger:
  - platform: state
    entity_id:
    - sensor.smart_series_9000_782c_toothbrush_state
    to: running
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.bathroom
      message: Teeth brushing done!
  mode: single
- id: '1668343727944'
  alias: Dehumidify at night (03:00 - 05:25)
  description: ''
  trigger:
  - platform: time
    at: 03:00:00
  - platform: time
    at: 05:25:00
  condition: []
  action:
  - if:
    - condition: time
      before: 05:00:00
      after: '22:00:00'
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.mystromservers
    else:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.mystromservers
  mode: single
- id: '1668943375956'
  alias: Turn on bar lights after sunset
  description: Turns on the bar lights 30min after sunset and when I'm home.
  trigger:
  - platform: sun
    event: sunset
    offset: 00:30
  condition:
  - condition: state
    entity_id: person.theo_winter
    state: home
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.bar_lights
  mode: single
- id: '1669748575150'
  alias: Xiaomi G10 Vacuum Charger - OFF after 1:30h
  description: Turns the vacuum charging station off after 1h to prevent the battery
    from going bad from continuous charging.
  trigger:
  - platform: state
    entity_id:
    - switch.mystromclickandgrow3
    from: 'off'
    to: 'on'
    for:
      hours: 1
      minutes: 30
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.mystromclickandgrow3
  mode: single
- id: '1683007339636'
  alias: Vacuum Charger Button
  description: Charge Vacuum when button is pressed
  trigger:
  - device_id: 8f318926b54166549248bfd6d40d724f
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.mystromclickandgrow3
  mode: single
