homeassistant:
  customize: !include customize.yaml

# Configures various services: updater, cloud, webhooks etc.
# https://www.home-assistant.io/integrations/default_config/
default_config:

frontend:
  themes: !include_dir_merge_named themes

ios:

browser_mod:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
recorder:
  db_url: !secret db_connection
  purge_keep_days: 30

sensor: # All sensors with multiple states
  - platform: openerz
    zip: 8048
    waste_type: cargotram, etram, organic, textile
  - platform: rest
    name: Migros Fitnesspark Puls 5
    resource: https://blfa-api.migros.ch/fp/api/center/6/currentuser
    verify_ssl: false
    value_template: '{{ value_json.currentVisitors }}'
    unit_of_measurement: "people"
    json_attributes:
      - currentVisitors
      - maxVisitors
  - platform: rest
    name: Flussbad Au-Höngg
    resource: https://baditicker.herokuapp.com
    device_class: temperature
    verify_ssl: false
    value_template: "{{ value_json.pools[0].temperature }}"
    unit_of_measurement: "C°"
    json_attributes_path: $.pools[0]
    json_attributes:
      - name
      - updatedAt
      - open
  - platform: rest
    name: Seebad Utoquai
    resource: https://baditicker.herokuapp.com
    device_class: temperature
    verify_ssl: false
    value_template: "{{ value_json.pools[14].temperature }}"
    unit_of_measurement: "C°"
    json_attributes_path: $.pools[14]
    json_attributes:
      - name
      - updatedAt
      - open
  - platform: rest
    name: Tumbler Power
    resource: http://192.168.178.144/report
    device_class: power
    value_template: "{{ value_json.power }}"
  - platform: rest
    name: Washing Machine Power
    resource: http://192.168.178.52/report
    device_class: power
    value_template: "{{ value_json.power }}"
  - platform: rest
    name: Dishwasher Power
    resource: http://192.168.178.392/report
    device_class: power
    value_template: "{{ value_json.power }}"
  - platform: rest
    name: Office Power
    resource: http://192.168.178.37/report
    device_class: power
    value_template: "{{ value_json.power }}"
  - platform: rest
    name: TV Utilities Power
    resource: http://192.168.178.40/report
    device_class: power
    value_template: "{{ value_json.power }}"
  - platform: fitbit
    monitored_resources:
      - "body/weight"
      - "body/fat"
  - platform: lastfm
    api_key: !secret last_fm_api_key
    users:
      - aerobless
  - platform: imap_email_content
    server: imap.gmail.com
    name: banking_email
    port: 993
    username: !secret gmail_user
    password: !secret gmail_password
    folder: UBS
    senders:
      - noreply-alerting@ubs.com
      - !secret gmail_user

sensor power: !include config/power-measurement-sensors.yaml

mqtt:
  sensor: !include_dir_merge_list  config/mqtt/sensor
  light: !include config/mqtt/shelly-lights.yaml
  binary_sensor: !include config/mqtt/shelly-light-switches.yaml
  switch:
    - name: "Kitchen Plug"
      state_topic: "shellies/shellyswitch25-98CDAC1ECBD4/relay/0"
      command_topic: "shellies/shellyswitch25-98CDAC1ECBD4/relay/0/command"
      payload_off: "off"
      payload_on: "on"

rest_command:
  get_plantgateway_status:
    url: https://192.168.178.63:8000
    method: GET
    verify_ssl: false
    username: !secret plant_gateway_username
    password: !secret plant_gateway_password
  print_shopping_list:
    url: https://192.168.178.57:8000
    method: POST
    verify_ssl: false
    username: !secret thermalprinter_username
    password: !secret thermalprinter_password

binary_sensor: # All sensors with just two states (ON/OFF)
  - platform: ping
    host: !secret samsung_tv_ip
    name: Samsung TV
    scan_interval: 30 # seconds
    count: 2
  - platform: template
    sensors:
        washingmachine_state:
            friendly_name: "Washing Machine State"
            delay_on:
                minutes: 3
            delay_off: # Only switches states after new state existed for x minutes
                minutes: 3
            icon_template: mdi:washing-machine
            value_template: "{{ states('sensor.washing_machine_power') | default(0) |float > 10}}"
        tumbler_state:
            friendly_name: "Tumbler State"
            delay_on:
                minutes: 3
            delay_off: # Only switches states after new state existed for x minutes
                minutes: 3
            icon_template: mdi:washing-machine
            value_template: "{{ states('sensor.tumbler_power') | default(0) |float > 10}}"
        dishwasher_state:
            friendly_name: "Dishwasher State"
            delay_off: # Only switches states after new state existed for x minutes
                minutes: 3
            icon_template: mdi:dishwasher
            value_template: "{{ states('sensor.dishwasher_power') | default(0) |float > 10}}"
        entrance_logi_motion:
            friendly_name: "Entrance Motion"
            device_class: motion
            value_template: "{{ is_state('input_boolean.homekit_entrance_logi_motion_relay', 'on') }}"
        livingroom_logi_motion:
            friendly_name: "Living Room Motion"
            device_class: motion
            value_template: "{{ is_state('input_boolean.homekit_livingroom_logi_motion_relay', 'on') }}"
        apartment_occupancy:
            friendly_name: "Apartment Occupancy"
            delay_on:
              minutes: 5
            delay_off:
              minutes: 3
            device_class: occupancy
            value_template: "{{ is_state('person.theo_winter', 'home') }}"
        intrusion_detection:
            friendly_name: "Intrusion Detection"
            device_class: motion
            value_template: "{{ is_state('input_boolean.intrusion_detection_sensor_switch', 'on') }}"
        bed_state:
            friendly_name: Bed
            device_class: occupancy
            icon_template: mdi:bed-empty
            value_template: "{{ is_state('input_boolean.bed_occupied_input', 'on') }}"

tts: !include config/tts-configuration.yaml

light:
  - platform: nanoleaf
    host: !secret nanoleaf_ip
    token: !secret nanoleaf_token
  - platform: switch
    name: Loggia Fairy Lights
    entity_id: switch.loggia_fairy_lights

light groups: !include config/light-groups.yaml
    
ifttt:
  key: !secret ifttt_key

cloud:

switch:
  - platform: template
    switches:
      samsung_tv:
        friendly_name: TV
        value_template: "{{ is_state('binary_sensor.samsung_tv', 'on') }}"
        turn_on:
            event: ACTION_TV_STATE_CHANGE
            event_data_template:
                tv_action: "tv_on"
        turn_off:
            event: ACTION_TV_STATE_CHANGE
            event_data_template:
                tv_action: "tv_off"
        icon_template: >-
          {% if is_state('binary_sensor.samsung_tv', 'on') %}
            mdi:television
          {% else %}
            mdi:television-off
          {% endif %}
      vacuum_control: #Used for frontend vacuum button (on/off/settings)
        friendly_name: Vacuum Control
        value_template: "{{ is_state('vacuum.roborock_s7', 'cleaning') }}"
        turn_on:
          service: vacuum.start
          entity_id: vacuum.roborock_s7
        turn_off:
          service: vacuum.return_to_base
          entity_id: vacuum.roborock_s7
      music_control:
        friendly_name: Music Control
        value_template: "{{ is_state('media_player.everywhere', 'playing') }}"
        icon_template: mdi:music
        turn_on:
          service: spotcast.start
          data:
            entity_id: media_player.everywhere
            uri: 'spotify:playlist:440DwvrtJWWM3v0AgRSRNx'
            shuffle: true
        turn_off:
          service: media_player.turn_off
          entity_id: media_player.everywhere

switch mystrom: !include config/mystrom-switches.yaml

input_boolean:
  play_energy_zurich_everywhere:
    name: Energy Zürich (everyhwere)
    initial: off
  homekit_entrance_logi_motion_relay: # Logi Camera Motion Sensor
    name: Logi Entrance Motion Sensor Relay
    initial: off
  homekit_livingroom_logi_motion_relay: # Logi Camera Motion Sensor
    name: Logi Living Room Motion Sensor Relay
    initial: off
  alarm_clock_enabled:
    name: Alarm Clock
    icon: mdi:alarm
  bed_occupied_input:
    name: Bed Occupied Input
    initial: off
    icon: mdi:bed-empty

input_datetime:
  work_week_alarm:
    name: Work Alarm
    has_date: false
    has_time: true
  weekend_alarm:
    name: Weekend Alarm
    has_date: false
    has_time: true
    
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_token
    allowed_chat_ids:
      - !secret telegram_chat_id

utility_meter:
  daily_energy:
    source: sensor.apartment_energy_consumption
    cycle: daily
    tariffs:
      - peak
      - offpeak

logi_circle:
  client_id: !secret logi_client_id
  client_secret: !secret logi_client_secret
  api_key: !secret logi_api_key
  redirect_uri: !secret logi_redirect_url

weather:
  - platform: darksky
    mode: daily
    api_key: !secret dark_sky_api_key

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

notify:
  - name: notify_all
    platform: group
    services:
      - service: mobile_app_theos_iphone_11

#octoprint:
#  host: !secret octoprint_ip
#  api_key: !secret octoprint_api_key
#  name: Creality Ender 3 v2
#  bed: true

# HACS integration: https://github.com/fondberg/spotcast
spotcast:
  sp_dc: !secret spotcast_dc
  sp_key: !secret spotcast_key

knx: !include config/knx.yaml
media_player: !include config/media_player.yaml
homekit: !include config/homekit.yaml
plant: !include config/plant.yaml
camera: !include config/camera.yaml
influxdb: !include config/influx-db.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml