homeassistant:
  customize: !include customize.yaml

default_config:

discovery:

scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

ios:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true
  
recorder:
  db_url: !secret db_connection
  purge_keep_days: 30

knx:
  tunneling:
    host: '192.168.178.71' #192.168.178.71
    port: 3671
  fire_event: true
  fire_event_filter: ["27/1-2/*", "*/*/*"]

sensor: # All sensors with multiple states
  - platform: mqtt
    name: "Bedroom Shelly Switch Temperature"
    state_topic: "shellies/shelly1pm-005D54/temperature"
    unit_of_measurement: '°C'
  - platform: mqtt
    name: "Bedroom Shelly Switch Energy"
    state_topic: "shellies/shelly1pm-005D54/relay/0/energy"
    unit_of_measurement: 'W/min'
  - platform: mqtt
    name: "Bedroom Shelly Switch Power"
    state_topic: "shellies/shelly1pm-005D54/relay/0/power"
    unit_of_measurement: 'W'
  - platform: mqtt
    name: "Bathroom Shelly Switch Temperature"
    state_topic: "shellies/shellyswitch25-5DB78A/temperature"
    unit_of_measurement: '°C'
  - platform: mqtt
    name: "Bathroom Shelly Switch Energy"
    state_topic: "shellies/shellyswitch25-5DB78A/relay/1/energy"
    unit_of_measurement: 'W/min'
  - platform: mqtt
    name: "Bathroom Shelly Switch Power"
    state_topic: "shellies/shellyswitch25-5DB78A/relay/1/power"
    unit_of_measurement: 'W'
  - platform: mqtt
    name: "Entrance Shelly Switch Temperature"
    state_topic: "shellies/shelly1pm-E67762/temperature"
    unit_of_measurement: '°C'
  - platform: mqtt
    name: "Entrance Shelly Switch Energy"
    state_topic: "shellies/shelly1pm-E67762/relay/0/energy"
    unit_of_measurement: 'W/min'
  - platform: mqtt
    name: "Entrance Shelly Switch Power"
    state_topic: "shellies/shelly1pm-E67762/relay/0/power"
    unit_of_measurement: 'W'
  - platform: mqtt
    name: "Living Room Shelly Switch 1 Temperature"
    state_topic: "shellies/shellyswitch25-6868E9/temperature"
    unit_of_measurement: '°C'
  - platform: mqtt
    name: "Living Room Shelly Switch TV Spot Energy"
    state_topic: "shellies/shellyswitch25-6868E9/relay/0/energy"
    unit_of_measurement: 'W/min'
  - platform: mqtt
    name: "Living Room Shelly Switch TV Spot Power"
    state_topic: "shellies/shellyswitch25-6868E9/relay/0/power"
    unit_of_measurement: 'W'
  - platform: mqtt
    name: "Living Room Shelly Switch Kitchen Table Energy"
    state_topic: "shellies/shellyswitch25-6868E9/relay/1/energy"
    unit_of_measurement: 'W/min'
  - platform: mqtt
    name: "Living Room Shelly Switch Kitchen Table Power"
    state_topic: "shellies/shellyswitch25-6868E9/relay/1/power"
    unit_of_measurement: 'W'
  - platform: mqtt
    name: "Living Room Shelly Switch 2 Temperature"
    state_topic: "shellies/shellyswitch25-686CEF/temperature"
    unit_of_measurement: '°C'
  - platform: mqtt
    name: "Living Room Shelly Switch Plug Energy"
    state_topic: "shellies/shellyswitch25-686CEF/relay/1/energy"
    unit_of_measurement: 'W/min'
  - platform: mqtt
    name: "Living Room Shelly Switch Plug Power"
    state_topic: "shellies/shellyswitch25-686CEF/relay/1/power"
    unit_of_measurement: 'W'
  - platform: mqtt
    name: "Kitchen Shelly Switch Temperature"
    state_topic: "shellies/shellyswitch25-00467D/temperature"
    unit_of_measurement: '°C'
  - platform: mqtt
    name: "Kitchen Shelly Switch Plug Energy"
    state_topic: "shellies/shellyswitch25-00467D/relay/0/energy"
    unit_of_measurement: 'W/min'
  - platform: mqtt
    name: "Kitchen Shelly Switch Plug Power"
    state_topic: "shellies/shellyswitch25-00467D/relay/0/power"
    unit_of_measurement: 'W'
  - platform: mqtt
    name: "Kitchen Shelly Switch Overhead Light Energy"
    state_topic: "shellies/shellyswitch25-00467D/relay/1/energy"
    unit_of_measurement: 'W/min'
  - platform: mqtt
    name: "Kitchen Shelly Switch Overhead Light Power"
    state_topic: "shellies/shellyswitch25-00467D/relay/1/power"
    unit_of_measurement: 'W'
  - platform: template
    sensors:
        washingmachine_power:
            friendly_name: "Washing Machine Power"
            icon_template: mdi:washing-machine
            unit_of_measurement: "W"
            value_template: "{{ states.switch.mystrom_washingmachine.attributes.current_power_w | default(0) }}"
        tumbler_power:
            friendly_name: "Tumbler Power"
            icon_template: mdi:dishwasher
            unit_of_measurement: "W"
            value_template: "{{ states.switch.mystrom_tumbler.attributes.current_power_w | default(0) }}"
        dishwasher_power:
            friendly_name: "Dishwasher Power"
            icon_template: mdi:dishwasher
            unit_of_measurement: "W"
            value_template: "{{ states.switch.mystrom_dishwasher.attributes.current_power_w | default(0) }}"
        total_power:
            friendly_name: "Total Power Usage"
            icon_template: mdi:power-plug
            unit_of_measurement: "W"
            value_template: "{{ ((states('sensor.living_room_shelly_switch_kitchen_table_power') | replace('unknown', '0') | round(2)) 
            + (state_attr('switch.mystromclickandgrow3','current_power_w') | replace('None', '0') | round(2))
            + (state_attr('switch.ebike_charger','current_power_w') | replace('None', '0') | round(2))
            + (state_attr('switch.mystromaquariumlight','current_power_w') | replace('None', '0') | round(2)) 
            + (state_attr('switch.mystromtvutilities','current_power_w') | replace('None', '0') | round(2))
            + (state_attr('switch.mystromimac','current_power_w') | replace('None', '0') | round(2))
            + (state_attr('switch.mystrom_washingmachine','current_power_w') | replace('None', '0') | round(2))
            + (state_attr('switch.mystrom_tumbler','current_power_w') | replace('None', '0') | round(2))
            + (state_attr('switch.mystrom_dishwasher','current_power_w') | replace('None', '0') | round(2))
            + (state_attr('switch.charging_station','current_power_w') | replace('None', '0') | round(2))
            + (states('sensor.bathroom_shelly_switch_power') | replace('unknown', '0') | round(2)) 
            + (states('sensor.bedroom_shelly_switch_power') | replace('unknown', '0') | round(2)) 
            + (states('sensor.entrance_shelly_switch_power') | replace('unknown', '0') | round(2)) 
            + (states('sensor.kitchen_shelly_switch_overhead_light_power') | replace('unknown', '0') | round(2)) 
            + (states('sensor.kitchen_shelly_switch_plug_power') | replace('unknown', '0') | round(2)) 
            + (states('sensor.living_room_shelly_switch_kitchen_table_power') | replace('unknown', '0') | round(2))
            + (states('sensor.living_room_shelly_switch_plug_power') | replace('unknown', '0') | round(2))
            + (states('sensor.living_room_shelly_switch_tv_spot_power') | replace('unknown', '0') | round(2))
            )|round(2)}}"
  - platform: openerz
    zip: 8048
    waste_type: cargotram, etram, organic, textile
  
sensor plants: !include config/plant-mqtt-sensor.yaml

rest_command:
  get_plantgateway_status:
    url: https://192.168.178.63:8000
    method: GET
    verify_ssl: false
    username: !secret plant_gateway_username
    password: !secret plant_gateway_password
  print_shopping_list:
    url: https://192.168.178.57:8000
    method: POST
    verify_ssl: false
    username: !secret thermalprinter_username
    password: !secret thermalprinter_password

binary_sensor: # All sensors with just two states (ON/OFF)
  - platform: ping
    host: 192.168.178.20 # Samsung TV
    name: Samsung TV
    scan_interval: 30 # seconds
    count: 2
  - platform: mqtt
    name: Bathroom Light Switch Short
    state_topic: "shellies/shellyswitch25-5DB78A/input/1"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Bedroom Light Switch Short
    state_topic: "shellies/shelly1pm-005D54/input/0"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Entrance Light Switch
    state_topic: "shellies/shelly1pm-E67762/input/0"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Living Room Light Switch 1
    state_topic: "shellies/shellyswitch25-6868E9/input/0"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Living Room Light Switch 2
    state_topic: "shellies/shellyswitch25-6868E9/input/1"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Living Room Light Switch 3
    state_topic: "shellies/shellyswitch25-686CEF/input/0"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Living Room Light Switch 4
    state_topic: "shellies/shellyswitch25-686CEF/input/1"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Kitchen Switch
    state_topic: "shellies/shellyswitch25-00467D/input/1"
    payload_on: "1"
    payload_off: "0"
  - platform: template
    sensors:
        washingmachine_state:
            friendly_name: "Washing Machine State"
            delay_on:
                minutes: 3
            delay_off: # Only switches states after new state existed for x minutes
                minutes: 3
            icon_template: mdi:washing-machine
            value_template: "{{ states.switch.mystrom_washingmachine.attributes.current_power_w | default(0) |float > 10}}"
        tumbler_state:
            friendly_name: "Tumbler State"
            delay_on:
                minutes: 3
            delay_off: # Only switches states after new state existed for x minutes
                minutes: 3
            icon_template: mdi:washing-machine
            value_template: "{{ states.switch.mystrom_tumbler.attributes.current_power_w | default(0) |float > 10}}"
        dishwasher_state:
            friendly_name: "Dishwasher State"
            delay_off: # Only switches states after new state existed for x minutes
                minutes: 3
            icon_template: mdi:dishwasher
            value_template: "{{ states.switch.mystrom_dishwasher.attributes.current_power_w | default(0) |float > 10}}"
        entrance_logi_motion:
            friendly_name: "Entrance Motion"
            device_class: motion
            value_template: "{{ is_state('input_boolean.homekit_entrance_logi_motion_relay', 'on') }}"
        livingroom_logi_motion:
            friendly_name: "Living Room Motion"
            device_class: motion
            value_template: "{{ is_state('input_boolean.homekit_livingroom_logi_motion_relay', 'on') }}"
        apartment_occupancy:
            friendly_name: "Apartment Occupancy"
            delay_on:
              minutes: 5
            delay_off:
              minutes: 3
            device_class: occupancy
            value_template: "{{ is_state('device_tracker.theosiphone', 'home') }}"
        intrusion_detection:
            friendly_name: "Intrusion Detection"
            device_class: motion
            value_template: "{{ is_state('input_boolean.intrusion_detection_sensor_switch', 'on') }}"
        bed_state:
            friendly_name: Bed
            device_class: occupancy
            icon_template: mdi:bed-empty
            value_template: "{{ is_state('input_boolean.bed_occupied_input', 'on') }}"
tts:
#  - platform: amazon_polly
#    aws_access_key_id: !secret aws_access_key_id
#    aws_secret_access_key: !secret aws_secret_access_key
#    region_name: eu-central-1
#    engine: neural
#    text_type: ssml
#    voice: Joanna
  - platform: google_cloud
    key_file: ttsgooglecloudsecret.json
    voice: en-US-Wavenet-C

light:
  - platform: nanoleaf
    host: 192.168.178.49
    token: !secret nanoleaf_token
  - platform: mqtt
    name: "Bathroom Light"
    state_topic: "shellies/shellyswitch25-5DB78A/relay/1"
    command_topic: "shellies/shellyswitch25-5DB78A/relay/1/command"
    payload_off: "off"
    payload_on: "on"
  - platform: mqtt
    name: "Kitchen Overhead Light"
    state_topic: "shellies/shellyswitch25-00467D/relay/1"
    command_topic: "shellies/shellyswitch25-00467D/relay/1/command"
    payload_off: "off"
    payload_on: "on"
  - platform: mqtt
    name: "Pixar Shelly"
    state_topic: "shellies/shellyswitch25-686CEF/relay/1"
    command_topic: "shellies/shellyswitch25-686CEF/relay/1/command"
    payload_off: "off"
    payload_on: "on"
  - platform: group
    name: Living Room Light Group
    entities:
      - light.tv_side_orb
      - light.tv_lightstrip
      - light.hue_go
      - light.living_room_spot_1
      - light.living_room_spot_2
      - light.living_room_spot_3
      - light.loggia_lightstrip
      - light.nanoleaf
      - light.eket_cubes
      - light.kitchen_table_light
  - platform: group
    name: Entrance Light Group
    entities:
      - light.hall_spot_1
      - light.hall_spot_2
  - platform: group
    name: Bedroom Light Group
    entities:
      - light.bedroom_swirl
      - light.bedside_orb
  - platform: group
    name: Loggia Light Group
    entities:
      - light.loggia_campfire
      - light.loggia_pixar
      - light.loggia_spot_1

climate:
  - platform: generic_thermostat
    name: netatmoInside
    heater: switch.fake
    target_sensor: sensor.netatmo_sixtymeters_indoor_temperature
    
ifttt:
  key: !secret ifttt_key

cloud:

switch:
  - platform: mqtt
    name: "Kitchen Plug"
    state_topic: "shellies/shellyswitch25-00467D/relay/0"
    command_topic: "shellies/shellyswitch25-00467D/relay/0/command"
    payload_off: "off"
    payload_on: "on"
  - platform: mystrom
    host: 192.168.178.39
    name: mystrom_dishwasher
  - platform: mystrom
    host: 192.168.178.58
    name: Charging Station
  - platform: mystrom
    host: 192.168.178.55
    name: eBike Charger
  - platform: mystrom
    host: 192.168.178.65
    name: myStromClickAndGrow3
  #- platform: mystrom
  #  host: 192.168.178.68
  #  name: myStromClickUnused
  - platform: mystrom
    host: 192.168.178.60
    name: mystrom_tumbler
  - platform: mystrom
    host: 192.168.178.52
    name: mystrom_washingmachine
  - platform: mystrom
    host: 192.168.178.40
    name: myStromTvUtilities
  - platform: mystrom
    host: 192.168.178.37
    name: myStromiMac
  - platform: mystrom
    host: 192.168.178.78
    name: myStromAquariumLight
  - platform: command_line
    switches:
      fake:
        command_on: echo "fake switch on"
        command_off: echo "fake switch on"
  - platform: template
    switches:
      samsung_tv:
        friendly_name: TV
        value_template: "{{ is_state('binary_sensor.samsung_tv', 'on') }}"
        turn_on:
            event: ACTION_TV_STATE_CHANGE
            event_data_template:
                tv_action: "tv_on"
        turn_off:
            event: ACTION_TV_STATE_CHANGE
            event_data_template:
                tv_action: "tv_off"
        icon_template: >-
          {% if is_state('binary_sensor.samsung_tv', 'on') %}
            mdi:television
          {% else %}
            mdi:television-off
          {% endif %}
        
cover:
  - platform: knx
    name: "Loggia"
    move_long_address: '27/1/230'
    move_short_address: '27/1/232'
    position_address: '27/1/231'
    position_state_address: '27/1/233'
    travelling_time_down: 24
    travelling_time_up: 24
  - platform: knx
    name: "Livingroom"
    move_long_address: '27/2/230'
    move_short_address: '27/2/232'
    position_address: '27/2/231'
    position_state_address: '27/2/233'
    travelling_time_down: 24
    travelling_time_up: 24
        
input_boolean:
  play_energy_zurich_everywhere:
    name: Energy Zürich (everyhwere)
    initial: off
  homekit_entrance_logi_motion_relay: # Logi Camera Motion Sensor
    name: Logi Entrance Motion Sensor Relay
    initial: off
  homekit_livingroom_logi_motion_relay: # Logi Camera Motion Sensor
    name: Logi Living Room Motion Sensor Relay
    initial: off
  alarm_clock_enabled:
    name: Alarm Clock
    icon: mdi:alarm
  bed_occupied_input:
    name: Bed Occupied Input
    initial: off
    icon: mdi:bed-empty

input_datetime:
  work_week_alarm:
    name: Work Alarm
    has_date: false
    has_time: true
  weekend_alarm:
    name: Weekend Alarm
    has_date: false
    has_time: true

#calendar:
#  - platform: todoist
#    token: !secret todoist_api_token
#    custom_projects:
#        - name: 'Due Today'
#          due_date_days: 1
#        - name: 'Due This Week'
#          due_date_days: 7
    
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_token
    allowed_chat_ids:
      - 131084571
    
lock:
  - platform: nello
    username: !secret nello_username
    password: !secret nello_password

remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.178.76

device_tracker:
  - platform: fritz
    interval_seconds: 30
    consider_home: 180
    new_device_defaults:
      track_new_devices: False

speedtestdotnet:
  scan_interval:
    minutes: 120
  monitored_conditions:
    - ping
    - download
    - upload

logi_circle:
  client_id: !secret logi_client_id
  client_secret: !secret logi_client_secret
  api_key: !secret logi_api_key
  redirect_uri: !secret logi_redirect_url

weather:
  - platform: darksky
    mode: daily
    api_key: !secret dark_sky_api_key

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

notify:
  - name: notify_all
    platform: group
    services:
      - service: mobile_app_theos_iphone_11

#spotcast:
#  username: !secret spotify_username
#  password: !secret spotify_password

media_player: !include config/media_player.yaml
homekit: !include config/homekit.yaml
plant: !include config/plant.yaml
camera: !include config/camera.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml