  - platform: mqtt
    name: Bathroom Light Switch Short
    state_topic: "shellies/shelly1-F4CFA2ED65C3/input/0"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Bedroom Light Switch Short
    state_topic: "shellies/shelly1pm-005D54/input/0"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Entrance Light Switch
    state_topic: "shellies/shelly1pm-E67762/input/0"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Living Room Light Switch 1
    state_topic: "shellies/shellyswitch25-68C63AF92D54/input/0"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Living Room Light Switch 2
    state_topic: "shellies/shellyswitch25-68C63AF92D54/input/1"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Living Room Light Switch 3
    state_topic: "shellies/shellyswitch25-686CEF/input/0"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Living Room Light Switch 4
    state_topic: "shellies/shellyswitch25-686CEF/input/1"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Kitchen Switch
    state_topic: "shellies/shellyswitch25-98CDAC1ECBD4/input/1"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: Loggia Light Switch
    state_topic: "shellies/shelly1pm-E5B612/input/0"
    payload_on: "1"
    payload_off: "0"