  - name: "Kitchen Plug"
    state_topic: "shellies/shellyswitch25-98CDAC1ECBD4/relay/0"
    command_topic: "shellies/shellyswitch25-98CDAC1ECBD4/relay/0/command"
    payload_off: "off"
    payload_on: "on"
  - name: "Living Room TV Plug"
    state_topic: "shellies/shellyswitch25-686CEF/relay/1"
    command_topic: "shellies/shellyswitch25-686CEF/relay/1/command"
    payload_off: "off"
    payload_on: "on"
  - name: "Living Room Desk Plug"
    state_topic: "shellies/shellyswitch25-686CEF/relay/0"
    command_topic: "shellies/shellyswitch25-686CEF/relay/0/command"
    payload_off: "off"
    payload_on: "on"