  - name: "Bathroom Light"
    state_topic: "shellies/shelly1-F4CFA2ED65C3/relay/0"
    command_topic: "shellies/shelly1-F4CFA2ED65C3/relay/0/command"
    payload_off: "off"
    payload_on: "on"
  - name: "Kitchen Overhead Light"
    state_topic: "shellies/shellyswitch25-98CDAC1ECBD4/relay/1"
    command_topic: "shellies/shellyswitch25-98CDAC1ECBD4/relay/1/command"
    payload_off: "off"
    payload_on: "on"
  - name: "Loggia Overhead Light"
    state_topic: "shellies/shelly1pm-E5B612/relay/0"
    command_topic: "shellies/shelly1pm-E5B612/relay/0/command"
    payload_off: "off"
    payload_on: "on"