host: a0d7b954-influxdb
port: 8086
database: homeassistant
username: !secret influx_username
password: !secret influx_password
max_retries: 3
default_measurement: state
include:
  entity_globs:
    - sensor.money_*
    - sensor.influx_*
    - sensor.*_account
    - sensor.*_balance
    - sensor.*_credit_card
    - sensor.eod_energy_*
    - sensor.health_*
    - sensor.yahoofinance_*
  entities:
    - sensor.migros_fitnesspark_puls_5
    - sensor.networth
    - sensor.bedroom_temperature
    - sensor.bathroom_temperature
    - sensor.loggia_shelly_ht_temperature
    - sensor.loggia_shelly_ht_humidity
    - sensor.fridge_temperature
    - sensor.loggia_temperature
    - sensor.office_temperature
    - sensor.netatmo_sixtymeters_indoor_temperature
    - sensor.kitchen_bin
    - binary_sensor.tumbler_state
    - binary_sensor.washingmachine_state
    - binary_sensor.dishwasher_state
    - sensor.flussbad_au_hongg
    - sensor.seebad_utoquai
    - binary_sensor.bed_state
    - binary_sensor.dishwasher_state
    - binary_sensor.tumbler_state
    - binary_sensor.washingmachine_state
    - input_datetime.weekend_alarm
    - input_datetime.work_week_alarm
    - vacuum.ghost
    - sensor.loggia_humidity
    - sensor.bathroom_humidity
    - sensor.office_humidity
    - sensor.fridge_humidity
    - sensor.netatmo_sixtymeters_indoor_humidity
    - sensor.netatmo_sixtymeters_indoor_co2
    - sensor.netatmo_sixtymeters_indoor_noise
    - sensor.netatmo_sixtymeters_indoor_pressure
    - person.theo_winter
    - binary_sensor.apartment_occupancy
    - sensor.aircon_mode
    - switch.aircon_power_on_off
    - sensor.swissquote_performance
    - sensor.swissquote_profit_percentage
    - sensor.experience_points
    - sensor.openweathermap_humidity
    - sensor.openweathermap_feels_like_temperature
    - sensor.openweathermap_temperature
    - sensor.openweathermap_snow
    - sensor.openweathermap_rain
    - sensor.openweathermap_wind_speed
    - sensor.sun_daylight