  - platform: group
    name: Living Room Light Group
    entities:
      - light.tv_side_orb
      - light.tv_lightstrip
      - light.hue_go
      - light.hue_shade
      - light.living_room_spot_1_window
      - light.living_room_spot_2_middle
      - light.living_room_spot_3_right
      - light.loggia_lightstrip
      - light.nanoleaf
      - light.eket_cubes
      - light.kitchen_table_light
  - platform: group
    name: Entrance Light Group
    entities:
      - light.entrance_spot_1_inner
      - light.entrance_spot_2_outer
  - platform: group
    name: Bedroom Light Group
    entities:
      - light.bedroom_swirl
      - light.bedside_orb
  - platform: group
    name: Loggia Light Group
    entities:
      - light.loggia_campfire
      - light.pixar_filament
      - light.loggia_spot_1