  - platform: template
    sensors:
        total_power:
            friendly_name: "Total Power Usage W"
            icon_template: mdi:power-plug
            unit_of_measurement: "W"
            value_template: "{{ ((states('sensor.shelly3em_channel_a_power') | replace('unknown', '0') | round(2)) 
            + (states('sensor.shelly3em_channel_b_power') | replace('unknown', '0') | round(2)) 
            + (states('sensor.shelly3em_channel_c_power') | replace('unknown', '0') | round(2)) 
            )|round(2)}}"
        daily_energy_total:
            friendly_name: Daily Energy Total
            unit_of_measurement: kWh
            value_template: "{{ states('sensor.daily_energy_offpeak')|float + states('sensor.daily_energy_peak')|float }}"
        # Tarif: ewz.econatur -- Peak 26.44 Rp./kWh -- Offpeak 15.24 Rp./kWh (state 14.04.2022)
        # https://www.ewz.ch/de/private/strom/tarife/tarifuebersicht.html
        daily_energy_cost_total:
            friendly_name: Daily Energy Cost Total
            unit_of_measurement: CHF
            value_template: "{{ ((states('sensor.daily_energy_offpeak')|float)*0.2644 + (states('sensor.daily_energy_peak')|float)*0.1524)| round(2) }}"
  - platform: integration
    source: sensor.total_power
    name: Apartment Energy Consumption
    unit_prefix: k