#  - platform: amazon_polly
#    aws_access_key_id: !secret aws_access_key_id
#    aws_secret_access_key: !secret aws_secret_access_key
#    region_name: eu-central-1
#    engine: neural
#    text_type: ssml
#    voice: Joanna
  - platform: google_cloud
    key_file: ttsgooglecloudsecret.json
    voice: en-US-Wavenet-C